services:
  pdfinator:
    image: ${DOCKER_REGISTRY-}pdfinator
    build:
      context: .
      dockerfile: PDFinator/Dockerfile
    depends_on:
      - sqlserverService
    networks:
    - weathernet
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
        - "80"
        - "443"
  sqlserverService:
    image: mcr.microsoft.com/mssql/server:latest
    hostname: sqlserverService
    container_name: sqlserverService
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: BigPassw0rd1
    volumes:
      - ./data/mssql:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - weathernet

networks:
  weathernet:
    driver: bridge
